name: papercups_flutter
description: Flutter implementation of the papercups.io chat widget, built with a webview and provides customization options. 
version: 1.0.1
homepage: https://github.com/aguilaair/papercups_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
