name: papercups_flutter
description: Native Flutter implementation of the papercups.io chat widget. 
version: 2.0.5
homepage: https://github.com/aguilaair/papercups_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  phoenix_socket: ^0.4.11
  http: '>=0.12.2 <0.14.0'
  flutter_markdown: '>=0.5.2 <0.7.0'
  timeago: '>=2.0.30 <4.0.0'
  intl: '>=0.16.1 <0.18.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3

flutter:
