name: papercups_flutter
description: Flutter implementation of the papercups.io chat widget, built with a webview and provides customization options. 
version: 2.0.0-alpha
homepage: https://github.com/aguilaair/papercups_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  phoenix_socket: ^0.4.8
  http: ^0.12.2
  flutter_markdown: ^0.5.1
  timeago: ^2.0.29

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:
